### ISSUE TITLE
& reference not compatible with esp-idf

### ISSUE THREAD

**Issue by shaneapowell** [RobTillaart/FastTrig#25]
Hi Rob.
I was going to try a few of your optimizations today with your latest code.
Unfortunately, the esp32-idf compiler doesn't like the references arg for your isincos256 function. espidf is primarily `C`

`void isincos256(uint32_t v, int &si, int &co);` and also the 
`void isincos(float v, float &si, float &co);`
https://github.com/RobTillaart/FastTrig/blob/f24882d80c0e3d7b6332a9c8711fc6f8eb53327c/FastTrig.h#L52

I changed the function prototype, and in code to use a `*` and it seems to be compiling now at least, but I've not actually switched to your isincos256 function yet.
`void isincos256(uint32_t v, int *si, int *co);`

**Comment by RobTillaart** [comment]
Hi,
Sounds like a bug as references do not exist in 'C'.
I'll try to fix it asap.

**Comment by RobTillaart** [comment]
@shaneapowell 
Created - https://github.com/RobTillaart/FastTrig/tree/develop with 2x fix + updated examples.
Please verify if this works with **esp-idf**

**Comment by RobTillaart** [comment]
Merged into master and released 0.3.2
